/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as LinksRouteImport } from './routes/links'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as ProfileAnalyzeRouteImport } from './routes/profile-analyze'
import { Route as RateLimitsRouteImport } from './routes/rate-limits'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiActionRouteImport } from './routes/api/action'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiBirdCredentialsRouteImport } from './routes/api/bird-credentials'
import { Route as ApiBirdCredentialsTestRouteImport } from './routes/api/bird-credentials-test'
import { Route as ApiBlocksRouteImport } from './routes/api/blocks'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiConfigModelsRouteImport } from './routes/api/config-models'
import { Route as ApiConversationRouteImport } from './routes/api/conversation'
import { Route as ApiDataSourcesRouteImport } from './routes/api/data-sources'
import { Route as ApiDigestArchiveDatesRouteImport } from './routes/api/digest-archive-dates'
import { Route as ApiDigestArchiveEntryRouteImport } from './routes/api/digest-archive-entry'
import { Route as ApiDigestArchiveStatusRouteImport } from './routes/api/digest-archive-status'
import { Route as ApiDigestScheduleRouteImport } from './routes/api/digest-schedule'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiLinkInsightsRouteImport } from './routes/api/link-insights'
import { Route as ApiLinkPreviewRouteImport } from './routes/api/link-preview'
import { Route as ApiNetworkMapRouteImport } from './routes/api/network-map'
import { Route as ApiPeriodDigestRouteImport } from './routes/api/period-digest'
import { Route as ApiPeriodDigestFreshnessRouteImport } from './routes/api/period-digest-freshness'
import { Route as ApiPeriodDigestMetadataRouteImport } from './routes/api/period-digest-metadata'
import { Route as ApiProfileAnalysisRouteImport } from './routes/api/profile-analysis'
import { Route as ApiProfileAnalysisMetadataRouteImport } from './routes/api/profile-analysis-metadata'
import { Route as ApiProfileHydrateRouteImport } from './routes/api/profile-hydrate'
import { Route as ApiPromptTemplatesRouteImport } from './routes/api/prompt-templates'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiSearchDiscussionRouteImport } from './routes/api/search-discussion'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiXurlRateLimitsRouteImport } from './routes/api/xurl-rate-limits'
import { Route as ProfilesHandleRouteImport } from './routes/profiles.$handle'
import { Route as ApiPromptPlaygroundPeriodDigestRouteImport } from './routes/api/prompt-playground.period-digest'
import { Route as ApiPromptPlaygroundProfileAnalysisRouteImport } from './routes/api/prompt-playground.profile-analysis'
import { Route as ApiPromptPlaygroundSearchDiscussionRouteImport } from './routes/api/prompt-playground.search-discussion'
import { Route as ApiPromptTemplatesResetRouteImport } from './routes/api/prompt-templates.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAnalyzeRoute = ProfileAnalyzeRouteImport.update({
  id: '/profile-analyze',
  path: '/profile-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLimitsRoute = RateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBirdCredentialsRoute = ApiBirdCredentialsRouteImport.update({
  id: '/api/bird-credentials',
  path: '/api/bird-credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBirdCredentialsTestRoute = ApiBirdCredentialsTestRouteImport.update({
  id: '/api/bird-credentials-test',
  path: '/api/bird-credentials-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigModelsRoute = ApiConfigModelsRouteImport.update({
  id: '/api/config-models',
  path: '/api/config-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationRoute = ApiConversationRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesRoute = ApiDataSourcesRouteImport.update({
  id: '/api/data-sources',
  path: '/api/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestArchiveDatesRoute = ApiDigestArchiveDatesRouteImport.update({
  id: '/api/digest-archive-dates',
  path: '/api/digest-archive-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestArchiveEntryRoute = ApiDigestArchiveEntryRouteImport.update({
  id: '/api/digest-archive-entry',
  path: '/api/digest-archive-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestArchiveStatusRoute = ApiDigestArchiveStatusRouteImport.update({
  id: '/api/digest-archive-status',
  path: '/api/digest-archive-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestScheduleRoute = ApiDigestScheduleRouteImport.update({
  id: '/api/digest-schedule',
  path: '/api/digest-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkInsightsRoute = ApiLinkInsightsRouteImport.update({
  id: '/api/link-insights',
  path: '/api/link-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkMapRoute = ApiNetworkMapRouteImport.update({
  id: '/api/network-map',
  path: '/api/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodDigestRoute = ApiPeriodDigestRouteImport.update({
  id: '/api/period-digest',
  path: '/api/period-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodDigestFreshnessRoute =
  ApiPeriodDigestFreshnessRouteImport.update({
    id: '/api/period-digest-freshness',
    path: '/api/period-digest-freshness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPeriodDigestMetadataRoute = ApiPeriodDigestMetadataRouteImport.update({
  id: '/api/period-digest-metadata',
  path: '/api/period-digest-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAnalysisRoute = ApiProfileAnalysisRouteImport.update({
  id: '/api/profile-analysis',
  path: '/api/profile-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAnalysisMetadataRoute =
  ApiProfileAnalysisMetadataRouteImport.update({
    id: '/api/profile-analysis-metadata',
    path: '/api/profile-analysis-metadata',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProfileHydrateRoute = ApiProfileHydrateRouteImport.update({
  id: '/api/profile-hydrate',
  path: '/api/profile-hydrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptTemplatesRoute = ApiPromptTemplatesRouteImport.update({
  id: '/api/prompt-templates',
  path: '/api/prompt-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDiscussionRoute = ApiSearchDiscussionRouteImport.update({
  id: '/api/search-discussion',
  path: '/api/search-discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXurlRateLimitsRoute = ApiXurlRateLimitsRouteImport.update({
  id: '/api/xurl-rate-limits',
  path: '/api/xurl-rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesHandleRoute = ProfilesHandleRouteImport.update({
  id: '/profiles/$handle',
  path: '/profiles/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptPlaygroundPeriodDigestRoute =
  ApiPromptPlaygroundPeriodDigestRouteImport.update({
    id: '/api/prompt-playground/period-digest',
    path: '/api/prompt-playground/period-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPromptPlaygroundProfileAnalysisRoute =
  ApiPromptPlaygroundProfileAnalysisRouteImport.update({
    id: '/api/prompt-playground/profile-analysis',
    path: '/api/prompt-playground/profile-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPromptPlaygroundSearchDiscussionRoute =
  ApiPromptPlaygroundSearchDiscussionRouteImport.update({
    id: '/api/prompt-playground/search-discussion',
    path: '/api/prompt-playground/search-discussion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPromptTemplatesResetRoute = ApiPromptTemplatesResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ApiPromptTemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/config': typeof ConfigRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/bird-credentials': typeof ApiBirdCredentialsRoute
  '/api/bird-credentials-test': typeof ApiBirdCredentialsTestRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/config': typeof ApiConfigRoute
  '/api/config-models': typeof ApiConfigModelsRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/digest-archive-dates': typeof ApiDigestArchiveDatesRoute
  '/api/digest-archive-entry': typeof ApiDigestArchiveEntryRoute
  '/api/digest-archive-status': typeof ApiDigestArchiveStatusRoute
  '/api/digest-schedule': typeof ApiDigestScheduleRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-freshness': typeof ApiPeriodDigestFreshnessRoute
  '/api/period-digest-metadata': typeof ApiPeriodDigestMetadataRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-analysis-metadata': typeof ApiProfileAnalysisMetadataRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/prompt-templates': typeof ApiPromptTemplatesRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/prompt-playground/period-digest': typeof ApiPromptPlaygroundPeriodDigestRoute
  '/api/prompt-playground/profile-analysis': typeof ApiPromptPlaygroundProfileAnalysisRoute
  '/api/prompt-playground/search-discussion': typeof ApiPromptPlaygroundSearchDiscussionRoute
  '/api/prompt-templates/reset': typeof ApiPromptTemplatesResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/config': typeof ConfigRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/bird-credentials': typeof ApiBirdCredentialsRoute
  '/api/bird-credentials-test': typeof ApiBirdCredentialsTestRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/config': typeof ApiConfigRoute
  '/api/config-models': typeof ApiConfigModelsRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/digest-archive-dates': typeof ApiDigestArchiveDatesRoute
  '/api/digest-archive-entry': typeof ApiDigestArchiveEntryRoute
  '/api/digest-archive-status': typeof ApiDigestArchiveStatusRoute
  '/api/digest-schedule': typeof ApiDigestScheduleRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-freshness': typeof ApiPeriodDigestFreshnessRoute
  '/api/period-digest-metadata': typeof ApiPeriodDigestMetadataRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-analysis-metadata': typeof ApiProfileAnalysisMetadataRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/prompt-templates': typeof ApiPromptTemplatesRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/prompt-playground/period-digest': typeof ApiPromptPlaygroundPeriodDigestRoute
  '/api/prompt-playground/profile-analysis': typeof ApiPromptPlaygroundProfileAnalysisRoute
  '/api/prompt-playground/search-discussion': typeof ApiPromptPlaygroundSearchDiscussionRoute
  '/api/prompt-templates/reset': typeof ApiPromptTemplatesResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/config': typeof ConfigRoute
  '/data-sources': typeof DataSourcesRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/network-map': typeof NetworkMapRoute
  '/profile-analyze': typeof ProfileAnalyzeRoute
  '/rate-limits': typeof RateLimitsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/bird-credentials': typeof ApiBirdCredentialsRoute
  '/api/bird-credentials-test': typeof ApiBirdCredentialsTestRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/config': typeof ApiConfigRoute
  '/api/config-models': typeof ApiConfigModelsRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/data-sources': typeof ApiDataSourcesRoute
  '/api/digest-archive-dates': typeof ApiDigestArchiveDatesRoute
  '/api/digest-archive-entry': typeof ApiDigestArchiveEntryRoute
  '/api/digest-archive-status': typeof ApiDigestArchiveStatusRoute
  '/api/digest-schedule': typeof ApiDigestScheduleRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/network-map': typeof ApiNetworkMapRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/period-digest-freshness': typeof ApiPeriodDigestFreshnessRoute
  '/api/period-digest-metadata': typeof ApiPeriodDigestMetadataRoute
  '/api/profile-analysis': typeof ApiProfileAnalysisRoute
  '/api/profile-analysis-metadata': typeof ApiProfileAnalysisMetadataRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/prompt-templates': typeof ApiPromptTemplatesRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/xurl-rate-limits': typeof ApiXurlRateLimitsRoute
  '/profiles/$handle': typeof ProfilesHandleRoute
  '/api/prompt-playground/period-digest': typeof ApiPromptPlaygroundPeriodDigestRoute
  '/api/prompt-playground/profile-analysis': typeof ApiPromptPlaygroundProfileAnalysisRoute
  '/api/prompt-playground/search-discussion': typeof ApiPromptPlaygroundSearchDiscussionRoute
  '/api/prompt-templates/reset': typeof ApiPromptTemplatesResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/config'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/bird-credentials'
    | '/api/bird-credentials-test'
    | '/api/blocks'
    | '/api/config'
    | '/api/config-models'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/digest-archive-dates'
    | '/api/digest-archive-entry'
    | '/api/digest-archive-status'
    | '/api/digest-schedule'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-freshness'
    | '/api/period-digest-metadata'
    | '/api/profile-analysis'
    | '/api/profile-analysis-metadata'
    | '/api/profile-hydrate'
    | '/api/prompt-templates'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
    | '/api/xurl-rate-limits'
    | '/profiles/$handle'
    | '/api/prompt-playground/period-digest'
    | '/api/prompt-playground/profile-analysis'
    | '/api/prompt-playground/search-discussion'
    | '/api/prompt-templates/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/config'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/bird-credentials'
    | '/api/bird-credentials-test'
    | '/api/blocks'
    | '/api/config'
    | '/api/config-models'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/digest-archive-dates'
    | '/api/digest-archive-entry'
    | '/api/digest-archive-status'
    | '/api/digest-schedule'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-freshness'
    | '/api/period-digest-metadata'
    | '/api/profile-analysis'
    | '/api/profile-analysis-metadata'
    | '/api/profile-hydrate'
    | '/api/prompt-templates'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
    | '/api/xurl-rate-limits'
    | '/profiles/$handle'
    | '/api/prompt-playground/period-digest'
    | '/api/prompt-playground/profile-analysis'
    | '/api/prompt-playground/search-discussion'
    | '/api/prompt-templates/reset'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/config'
    | '/data-sources'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/network-map'
    | '/profile-analyze'
    | '/rate-limits'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/bird-credentials'
    | '/api/bird-credentials-test'
    | '/api/blocks'
    | '/api/config'
    | '/api/config-models'
    | '/api/conversation'
    | '/api/data-sources'
    | '/api/digest-archive-dates'
    | '/api/digest-archive-entry'
    | '/api/digest-archive-status'
    | '/api/digest-schedule'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/network-map'
    | '/api/period-digest'
    | '/api/period-digest-freshness'
    | '/api/period-digest-metadata'
    | '/api/profile-analysis'
    | '/api/profile-analysis-metadata'
    | '/api/profile-hydrate'
    | '/api/prompt-templates'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
    | '/api/xurl-rate-limits'
    | '/profiles/$handle'
    | '/api/prompt-playground/period-digest'
    | '/api/prompt-playground/profile-analysis'
    | '/api/prompt-playground/search-discussion'
    | '/api/prompt-templates/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  BookmarksRoute: typeof BookmarksRoute
  ConfigRoute: typeof ConfigRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DiscussRoute: typeof DiscussRoute
  DmsRoute: typeof DmsRoute
  InboxRoute: typeof InboxRoute
  LikesRoute: typeof LikesRoute
  LinksRoute: typeof LinksRoute
  MentionsRoute: typeof MentionsRoute
  NetworkMapRoute: typeof NetworkMapRoute
  ProfileAnalyzeRoute: typeof ProfileAnalyzeRoute
  RateLimitsRoute: typeof RateLimitsRoute
  TodayRoute: typeof TodayRoute
  ApiActionRoute: typeof ApiActionRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBirdCredentialsRoute: typeof ApiBirdCredentialsRoute
  ApiBirdCredentialsTestRoute: typeof ApiBirdCredentialsTestRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiConfigModelsRoute: typeof ApiConfigModelsRoute
  ApiConversationRoute: typeof ApiConversationRoute
  ApiDataSourcesRoute: typeof ApiDataSourcesRoute
  ApiDigestArchiveDatesRoute: typeof ApiDigestArchiveDatesRoute
  ApiDigestArchiveEntryRoute: typeof ApiDigestArchiveEntryRoute
  ApiDigestArchiveStatusRoute: typeof ApiDigestArchiveStatusRoute
  ApiDigestScheduleRoute: typeof ApiDigestScheduleRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiLinkInsightsRoute: typeof ApiLinkInsightsRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  ApiNetworkMapRoute: typeof ApiNetworkMapRoute
  ApiPeriodDigestRoute: typeof ApiPeriodDigestRoute
  ApiPeriodDigestFreshnessRoute: typeof ApiPeriodDigestFreshnessRoute
  ApiPeriodDigestMetadataRoute: typeof ApiPeriodDigestMetadataRoute
  ApiProfileAnalysisRoute: typeof ApiProfileAnalysisRoute
  ApiProfileAnalysisMetadataRoute: typeof ApiProfileAnalysisMetadataRoute
  ApiProfileHydrateRoute: typeof ApiProfileHydrateRoute
  ApiPromptTemplatesRoute: typeof ApiPromptTemplatesRouteWithChildren
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSearchDiscussionRoute: typeof ApiSearchDiscussionRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiXurlRateLimitsRoute: typeof ApiXurlRateLimitsRoute
  ProfilesHandleRoute: typeof ProfilesHandleRoute
  ApiPromptPlaygroundPeriodDigestRoute: typeof ApiPromptPlaygroundPeriodDigestRoute
  ApiPromptPlaygroundProfileAnalysisRoute: typeof ApiPromptPlaygroundProfileAnalysisRoute
  ApiPromptPlaygroundSearchDiscussionRoute: typeof ApiPromptPlaygroundSearchDiscussionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-analyze': {
      id: '/profile-analyze'
      path: '/profile-analyze'
      fullPath: '/profile-analyze'
      preLoaderRoute: typeof ProfileAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limits': {
      id: '/rate-limits'
      path: '/rate-limits'
      fullPath: '/rate-limits'
      preLoaderRoute: typeof RateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bird-credentials': {
      id: '/api/bird-credentials'
      path: '/api/bird-credentials'
      fullPath: '/api/bird-credentials'
      preLoaderRoute: typeof ApiBirdCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bird-credentials-test': {
      id: '/api/bird-credentials-test'
      path: '/api/bird-credentials-test'
      fullPath: '/api/bird-credentials-test'
      preLoaderRoute: typeof ApiBirdCredentialsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config-models': {
      id: '/api/config-models'
      path: '/api/config-models'
      fullPath: '/api/config-models'
      preLoaderRoute: typeof ApiConfigModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources': {
      id: '/api/data-sources'
      path: '/api/data-sources'
      fullPath: '/api/data-sources'
      preLoaderRoute: typeof ApiDataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-archive-dates': {
      id: '/api/digest-archive-dates'
      path: '/api/digest-archive-dates'
      fullPath: '/api/digest-archive-dates'
      preLoaderRoute: typeof ApiDigestArchiveDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-archive-entry': {
      id: '/api/digest-archive-entry'
      path: '/api/digest-archive-entry'
      fullPath: '/api/digest-archive-entry'
      preLoaderRoute: typeof ApiDigestArchiveEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-archive-status': {
      id: '/api/digest-archive-status'
      path: '/api/digest-archive-status'
      fullPath: '/api/digest-archive-status'
      preLoaderRoute: typeof ApiDigestArchiveStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-schedule': {
      id: '/api/digest-schedule'
      path: '/api/digest-schedule'
      fullPath: '/api/digest-schedule'
      preLoaderRoute: typeof ApiDigestScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-insights': {
      id: '/api/link-insights'
      path: '/api/link-insights'
      fullPath: '/api/link-insights'
      preLoaderRoute: typeof ApiLinkInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network-map': {
      id: '/api/network-map'
      path: '/api/network-map'
      fullPath: '/api/network-map'
      preLoaderRoute: typeof ApiNetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest': {
      id: '/api/period-digest'
      path: '/api/period-digest'
      fullPath: '/api/period-digest'
      preLoaderRoute: typeof ApiPeriodDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest-freshness': {
      id: '/api/period-digest-freshness'
      path: '/api/period-digest-freshness'
      fullPath: '/api/period-digest-freshness'
      preLoaderRoute: typeof ApiPeriodDigestFreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest-metadata': {
      id: '/api/period-digest-metadata'
      path: '/api/period-digest-metadata'
      fullPath: '/api/period-digest-metadata'
      preLoaderRoute: typeof ApiPeriodDigestMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-analysis': {
      id: '/api/profile-analysis'
      path: '/api/profile-analysis'
      fullPath: '/api/profile-analysis'
      preLoaderRoute: typeof ApiProfileAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-analysis-metadata': {
      id: '/api/profile-analysis-metadata'
      path: '/api/profile-analysis-metadata'
      fullPath: '/api/profile-analysis-metadata'
      preLoaderRoute: typeof ApiProfileAnalysisMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-hydrate': {
      id: '/api/profile-hydrate'
      path: '/api/profile-hydrate'
      fullPath: '/api/profile-hydrate'
      preLoaderRoute: typeof ApiProfileHydrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-templates': {
      id: '/api/prompt-templates'
      path: '/api/prompt-templates'
      fullPath: '/api/prompt-templates'
      preLoaderRoute: typeof ApiPromptTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-discussion': {
      id: '/api/search-discussion'
      path: '/api/search-discussion'
      fullPath: '/api/search-discussion'
      preLoaderRoute: typeof ApiSearchDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xurl-rate-limits': {
      id: '/api/xurl-rate-limits'
      path: '/api/xurl-rate-limits'
      fullPath: '/api/xurl-rate-limits'
      preLoaderRoute: typeof ApiXurlRateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$handle': {
      id: '/profiles/$handle'
      path: '/profiles/$handle'
      fullPath: '/profiles/$handle'
      preLoaderRoute: typeof ProfilesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-playground/period-digest': {
      id: '/api/prompt-playground/period-digest'
      path: '/api/prompt-playground/period-digest'
      fullPath: '/api/prompt-playground/period-digest'
      preLoaderRoute: typeof ApiPromptPlaygroundPeriodDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-playground/profile-analysis': {
      id: '/api/prompt-playground/profile-analysis'
      path: '/api/prompt-playground/profile-analysis'
      fullPath: '/api/prompt-playground/profile-analysis'
      preLoaderRoute: typeof ApiPromptPlaygroundProfileAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-playground/search-discussion': {
      id: '/api/prompt-playground/search-discussion'
      path: '/api/prompt-playground/search-discussion'
      fullPath: '/api/prompt-playground/search-discussion'
      preLoaderRoute: typeof ApiPromptPlaygroundSearchDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-templates/reset': {
      id: '/api/prompt-templates/reset'
      path: '/reset'
      fullPath: '/api/prompt-templates/reset'
      preLoaderRoute: typeof ApiPromptTemplatesResetRouteImport
      parentRoute: typeof ApiPromptTemplatesRoute
    }
  }
}

interface ApiPromptTemplatesRouteChildren {
  ApiPromptTemplatesResetRoute: typeof ApiPromptTemplatesResetRoute
}

const ApiPromptTemplatesRouteChildren: ApiPromptTemplatesRouteChildren = {
  ApiPromptTemplatesResetRoute: ApiPromptTemplatesResetRoute,
}

const ApiPromptTemplatesRouteWithChildren =
  ApiPromptTemplatesRoute._addFileChildren(ApiPromptTemplatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  BookmarksRoute: BookmarksRoute,
  ConfigRoute: ConfigRoute,
  DataSourcesRoute: DataSourcesRoute,
  DiscussRoute: DiscussRoute,
  DmsRoute: DmsRoute,
  InboxRoute: InboxRoute,
  LikesRoute: LikesRoute,
  LinksRoute: LinksRoute,
  MentionsRoute: MentionsRoute,
  NetworkMapRoute: NetworkMapRoute,
  ProfileAnalyzeRoute: ProfileAnalyzeRoute,
  RateLimitsRoute: RateLimitsRoute,
  TodayRoute: TodayRoute,
  ApiActionRoute: ApiActionRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBirdCredentialsRoute: ApiBirdCredentialsRoute,
  ApiBirdCredentialsTestRoute: ApiBirdCredentialsTestRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiConfigModelsRoute: ApiConfigModelsRoute,
  ApiConversationRoute: ApiConversationRoute,
  ApiDataSourcesRoute: ApiDataSourcesRoute,
  ApiDigestArchiveDatesRoute: ApiDigestArchiveDatesRoute,
  ApiDigestArchiveEntryRoute: ApiDigestArchiveEntryRoute,
  ApiDigestArchiveStatusRoute: ApiDigestArchiveStatusRoute,
  ApiDigestScheduleRoute: ApiDigestScheduleRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiLinkInsightsRoute: ApiLinkInsightsRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  ApiNetworkMapRoute: ApiNetworkMapRoute,
  ApiPeriodDigestRoute: ApiPeriodDigestRoute,
  ApiPeriodDigestFreshnessRoute: ApiPeriodDigestFreshnessRoute,
  ApiPeriodDigestMetadataRoute: ApiPeriodDigestMetadataRoute,
  ApiProfileAnalysisRoute: ApiProfileAnalysisRoute,
  ApiProfileAnalysisMetadataRoute: ApiProfileAnalysisMetadataRoute,
  ApiProfileHydrateRoute: ApiProfileHydrateRoute,
  ApiPromptTemplatesRoute: ApiPromptTemplatesRouteWithChildren,
  ApiQueryRoute: ApiQueryRoute,
  ApiSearchDiscussionRoute: ApiSearchDiscussionRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiXurlRateLimitsRoute: ApiXurlRateLimitsRoute,
  ProfilesHandleRoute: ProfilesHandleRoute,
  ApiPromptPlaygroundPeriodDigestRoute: ApiPromptPlaygroundPeriodDigestRoute,
  ApiPromptPlaygroundProfileAnalysisRoute:
    ApiPromptPlaygroundProfileAnalysisRoute,
  ApiPromptPlaygroundSearchDiscussionRoute:
    ApiPromptPlaygroundSearchDiscussionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
